### ISSUE TITLE
Helper called without trailing "()" does not warn

### ISSUE THREAD

**Issue by mjstahl** [canjs/can-stache#638] opened 2018-11-28 18:25 UTC
TL;DR
https://codepen.io/kphillips86/pen/XyxYgo

Assuming a helper:

```js
stache.addHelper('helloWorld', function helloWorld(options) { ... });
```

And a stache file that uses that helper:

```handlebars
{{#helloWorld}}
  <p>is rendered</p>
{{else}}
  <p>is NOT rendered
{{/helloWorld}}
```

`helloWorld` will not be executed, or is there a warning on the console that the helper should be called like `helloWorld()`.

Also, oddly enough the "truthy" section of the condition is rendered.

**Comment by chasenlehara** [comment] 2018-11-28 19:17
I think this is the expected behavior. My understanding is: stache is looking for `helloWorld` and it finds it (the helper is defined). The helper won’t be called (I think that was removed as of 4.x) and the truthy part will be rendered because `helloWorld` is defined.

**Comment by chasenlehara** [comment] 2018-12-26 18:17
I’m closing this issue because I think it’s the expected behavior (see my comment above).

If I’m wrong, please feel free to reopen this. 😊

**Closed by chasenlehara** 2018-12-26 18:17 UTC
