### ISSUE TITLE
Unnecessary Warnings for "Unable to find helper"

### ISSUE THREAD

**Issue by James0x57** [canjs/can-stache#483] opened 2018-03-01 22:46 UTC
https://jsbin.com/deyituvazi/1/edit?js,console,output

```
can.Component.extend({
  tag: 'rich-text-editor',
  view: `
    <div title="{{test}}">{{test2}}</div>
  `,
  ViewModel: {
    test: {default:'foo'},
    test2: {default:'bar'}
  }
});
```

test prop being used as an attribute value causes this warning to get logged:
`can-stache/expressions/helper.js: Unable to find helper "test".`

The binding syntax `title:from="test"` does not log this warning

**Comment by phillipskevin** [comment] 2018-03-02 02:46
Confirmed this is a duplicate of https://github.com/canjs/can-stache/issues/477 which was fixed in `can-stache@4.1.4` and will be included in `can@4.1.0`.

**Closed by phillipskevin** 2018-03-02 02:46 UTC
