### ISSUE TITLE
Add support for JavaScript like AND/OR operations in expressions

### ISSUE THREAD

**Issue by imaustink** [canjs/can-stache#565] opened 2018-07-10 19:13 UTC
I often wish stache expressions supported JS like AND/OR operations, something like this:
```mustache
{{#if(foo && bar || baz)}}
  <p>Hello World!</p>
{{/if}}
```

If you don't want to involve helpers, the alternative is something like this:
```mustache
{{#if(foo)}}
  {{#if(bar)}}
    <p>Hello World!</p>
  {{/if}}
{{else}}
  {{#if(baz)}}
    <p>Hello World!</p>
  {{/if}}
{{/if}}
```

My main problems with this are:
1. It is much harder to read and understand
2. It is much less compact
3. It creates duplicated code
4. It feels almost hacky

Although using a helper can solve the above problems, that means breaking out some of your template logic into viewModel which I don't think it the right place for these kinds of things, and from an organizational standpoint this seems messy.

Of course, you could create global `and`/`or` helpers like @christopherjbaker has suggested in #474, but even then the solution is less than ideal in my opinion.
```
{{#if(or(and(foo, bar), baz))}}
  <p>Hello World!</p>
{{/if}}
```

From an adoption standpoint, I think this is really valuable. If someone from the React or Vue community or even someone new to frontend frameworks starts playing with CanJS, this feels strange and even a bit confusing. It's not a monumental obstacle to overcome, but I think if we can reasonable remove any friction from the learning process, we should.

**Comment by justinbmeyer** [comment] 2018-07-10 20:11
You can create an “or” or “and” helper.

**Comment by christopherjbaker** [comment] 2018-07-10 20:42
With the presence of a ViewModel (unlike react/vue), wouldn't that be the correct place for this sort of logic? In this case, I would create a `sensiblyNamedProperty` or `sensiblyNamedFunction` on the vm that contains the appropriate logic.

**Comment by chasenlehara** [comment] 2018-07-11 17:46
I’m closing this as a duplicate of https://github.com/canjs/can-stache/issues/489

**Closed by chasenlehara** 2018-07-11 17:46 UTC
Labels: enhancement

**Comment by imaustink** [comment] 2018-07-11 17:52
@christopherjbaker I would still argue the VM is not the correct place for something like this. It seems like we're now breaking up basic templating logic into 2 different places. I think there is value in being able to fully understand the template without looking at the viewModel, by providing these features in the template, we're getting closer to that.
