### ISSUE TITLE
Cannot dynamically set attributes on the body tag

### ISSUE THREAD

**Issue by imaustink** [canjs/can-stache#457] opened 2018-01-31 03:38 UTC
Trying to dynamically set an attribute on the body tag does not work. Consider the following example:

`app.js`:
```
...
const vm = DefineMap({
  print: true
});
...
```
`index.stache`:
```
...
<body {{#if print}}class="print"{{/if}}>
...
```

I would expect the body to be rendered as `<body class="print">`, but it is instead rendered as `<body>`.

**Comment by justinbmeyer** [comment] 2018-01-31 04:01
This is really a bug with done-autorender

**Comment by justinbmeyer** [comment] 2018-01-31 04:02
I don’t really have a good idea how to fix it. Perhaps can-view-live can give access to what it’s doing so it’s doings can be moved to another element.

**Comment by matthewp** [comment] 2018-01-31 11:37
I think the problem is that done-autorender doesn't swap out your body tag. It probably can though.

**Comment by frank-dspeed** [comment] 2018-02-15 20:33
@matthewp @justinbmeyer @imaustink 

we have user using this in production with done ssr 2 and it works with canjs 4
gitter
```
Gregg Roemhildt @roemhildtg 20:24
This works:
<body data-root="{{env.ROOT}}">
document.body.getAttribute('data-root');

Kevin Phillips @phillipskevin 20:24


Gregg Roemhildt @roemhildtg 20:24


Kevin Phillips @phillipskevin 20:25
that probably only works because of the bug you mentioned, right @frank-dspeed ?

Frank Lemanschik @frank-dspeed 20:25
@roemhildtg what version of canjs is that

Kevin Phillips @phillipskevin 20:25
if the <body> were swapped out client side, that attribute might get overwritten

Gregg Roemhildt @roemhildtg 20:25
Hmm
This is canjs 4

Frank Lemanschik @frank-dspeed 20:26
maybe its fixed i will search around
there is a issue about exactly that scenario with body autorender="false"

Gregg Roemhildt @roemhildtg 20:27
I remember having an issue assigning "class" to abody
I had something like this not working:
body {{#if(something)}}class="something"{{/if}}

Frank Lemanschik @frank-dspeed 20:27
yes
but that should work now also
if your current example works
maybe justin has fixed it
he pointed that out

Gregg Roemhildt @roemhildtg 20:30
This is all working:
<body data-root="{{env.ROOT}}" {{#if(activeComponentProps.path)}}class="something"{{/if}}>
class and data-root get rendered

Frank Lemanschik @frank-dspeed 20:31
@phillipskevin canjs/can-stache#457
if that what @roemhildtg reports is true that issue is false
```

**Comment by justinbmeyer** [comment] 2019-04-24 15:57
seems like this is fixed now

**Closed by justinbmeyer** 2019-04-24 15:57 UTC
